"""One-step lookahead in the true simulator: what the week's action is worth when you can try it and see.

    PYTHONPATH=src .venv/bin/python lab/anastasiia/rl_lab/action_search.py --task=small --episodes=12

Every week the state is snapshotted. A handful of candidate actions is tried: for each, the state is restored, the
candidate played, and the rest of the episode finished by the plain rules. The candidate whose finished episode
costs least is the one actually played, and the search moves to the next week.

Two things make this worth measuring. It needs no model of the simulator — it *is* the simulator, so the gap that
sank the weekly linear program (87 billion USD per episode between what the plan assumed and what the simulator
did) is zero by construction. And it is the same machinery an agent could run at play time: the snapshot restores
to the cent, a whole episode plays in 0.04 s, and the state is recoverable from the observation.

With ``--foresight`` the tail is the true future, which makes this a ceiling. Without it the tail is still the
true future here (the simulator cannot be asked to forget), so read the number as "what a perfect forecast would
give a one-step lookahead", an upper bound on the causal version.

Candidates are generated by scaling the rules' own request for one family of commodities at a time — a
coordinate pass — so the search stays inside what an agent can actually ask for.
"""

import copy
import json
import sys
import time
from concurrent.futures import ProcessPoolExecutor
from pathlib import Path

import numpy as np


HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[2]
sys.path.insert(0, str(HERE))
sys.path.insert(0, str(ROOT / "src"))

import tuned_rules as T  # noqa: E402


_STATE = {}
# the families a candidate may scale, and the factors tried for each
FAMILIES = (("lng", "crude", "nucfuel"), ("wafer",), ("chip_le_raw", "chip_mat_raw"), ("chip_le", "chip_mat"))
FACTORS = (0.0, 0.5, 0.8, 1.0, 1.25, 1.6, 2.5)


def groups_of(config, grouping):
    """``[(name, mask over slots)]`` — what one coordinate of the search may scale.

    ``family`` gives four coordinates: all the fuel, all the wafers, all the raw chips, all the finished chips. That
    is a blunt instrument: the move ``hub/FINDINGS.md`` measures as valuable is taking fuel from one grid and giving
    it to another, and no single factor over all the fuel can do it. ``destination`` splits every family by where
    the cargo is going — one coordinate per (destination, family) — which is the finest grouping that still leaves
    the search affordable.
    """
    static = config["static"]
    slots, edges, lanes = static["action_slots"], static["edges"], static["lanes"]
    names, commodities = static["nodes"]["id"], static["commodities"]["id"]
    route = [lanes["edges"][ln] if ln is not None else [e] for e, ln in zip(slots["edge"], slots["lane"])]
    dest = np.array([int(edges["head"][r[-1]]) for r in route])
    slot_k = np.array([int(k) for k in slots["k"]])
    fam_index = -np.ones(len(commodities), dtype=int)
    for j, fam in enumerate(FAMILIES):
        for c in fam:
            if c in commodities:
                fam_index[commodities.index(c)] = j
    fam_of_slot = fam_index[slot_k]

    if grouping == "family":
        return [(f"family:{j}", fam_of_slot == j) for j in range(len(FAMILIES))]
    if grouping == "destination":
        out = []
        for j in range(len(FAMILIES)):
            for node in sorted(set(dest[fam_of_slot == j].tolist())):
                out.append((f"{names[node]}/{j}", (fam_of_slot == j) & (dest == node)))
        return out
    if grouping == "commodity":  # one coordinate per (destination, commodity)
        out = []
        for k in sorted(set(slot_k.tolist())):
            for node in sorted(set(dest[slot_k == k].tolist())):
                out.append((f"{names[node]}/{commodities[k]}", (slot_k == k) & (dest == node)))
        return out
    if grouping == "slot":  # the finest there is: every action slot on its own, so this bounds the whole family
        n = len(slot_k)
        return [(f"slot:{s}", np.arange(n) == s) for s in range(n)]
    raise ValueError(f"grouping must be family, destination, commodity or slot, got {grouping!r}")


def _env(task, entropy, n_scenarios):
    import gymnasium as gym
    from shockbench_flow_gym.wrappers import ScenarioPool

    from sbf_starter import env_id

    key = (task, entropy, n_scenarios)
    if key not in _STATE:
        _STATE[key] = ScenarioPool(gym.make(env_id(task), regime="standard"), n_scenarios, entropy)
    if "parts" not in _STATE:
        _STATE["parts"] = T.Parts()
    return _STATE[key], _STATE["parts"]


# Exactly what a week changes on the adapter, found by comparing every attribute across one step: the simulator
# itself, and the adapter's own week counter — missing the second leaves a restored episode a week out of step.
# ``omega_source`` also changes, but it belongs to the scenario pool, which checks that its own object was the one
# drawn: a copy of it breaks the next reset, and the scenario does not change inside an episode anyway.
MUTABLE = ("core", "_week", "np_random")


def _snapshot(env):
    """The parts of the adapter a week changes. Verified to restore a step, and a whole tail, to the cent."""
    inner = env.unwrapped
    return {k: copy.deepcopy(getattr(inner, k)) for k in MUTABLE if hasattr(inner, k)}


def _restore(env, snap):
    inner = env.unwrapped
    for k, v in snap.items():
        setattr(inner, k, copy.deepcopy(v))


def _finish(env, parts, config, obs, first_action, week, schedule, masks):
    """Play ``first_action``, then finish the episode on the schedule found so far. Returns what the rest cost.

    The tail matters more than it looks. With the plain rules in it, a week's deviation is judged alone, and a
    strategy that only pays off if it is held for several weeks — turning a grid off to bank its fuel, which
    ``hub/FINDINGS.md`` measures as the valuable move — always looks like a loss and is rejected. Replaying the
    schedule instead lets a sweep build on the last one.
    """
    total = 0.0
    obs, reward, terminated, truncated, _ = env.step(first_action)
    total += -float(reward)
    if terminated or truncated:
        return total
    agent = parts.agent(config, None)
    w = week + 1
    while True:
        proposal = agent.act(obs)
        flows = np.asarray(proposal["flows"], dtype=np.float64)
        if schedule is not None and w < schedule.shape[0]:
            scale = np.ones(flows.shape[0])
            for j, mask in enumerate(masks):
                scale[mask] = schedule[w, j]
            proposal = {**proposal, "flows": flows * scale}
        obs, reward, terminated, truncated, _ = env.step(proposal)
        total += -float(reward)
        w += 1
        if terminated or truncated:
            return total


def episode(payload):
    """One episode played with a one-step lookahead each week. Returns its cost and the plain rules' for comparison."""
    from shockbench_flow_gym import agent_config_from_reset

    task, entropy, n_scenarios, index, sweeps, grouping = payload
    env, parts = _env(task, entropy, n_scenarios)

    obs, info = env.reset(options={"pool_index": int(index)})
    config = agent_config_from_reset(env, obs, info)
    base_agent = parts.agent(config, None)
    base = 0.0
    while True:
        obs, reward, terminated, truncated, _ = env.step(base_agent.act(obs))
        base += -float(reward)
        if terminated or truncated:
            break

    groups = groups_of(config, grouping)
    masks = [m for _, m in groups]
    weeks = int(config["T"])

    schedule = np.ones((weeks, len(groups)))
    best_total, rollouts, history = base, 0, []
    for _ in range(max(1, sweeps)):
        obs, info = env.reset(options={"pool_index": int(index)})
        agent = parts.agent(config, None)
        found = schedule.copy()
        total, w = 0.0, 0
        while True:
            proposal = agent.act(obs)
            flows = np.asarray(proposal["flows"], dtype=np.float64)
            snap = _snapshot(env)
            scale = np.ones(flows.shape[0])
            for j, mask in enumerate(masks):
                scale[mask] = found[w, j]
            best_cost = None
            for j, mask in enumerate(masks):  # one coordinate at a time over the week's action
                if not np.any(flows[mask] > 0.0):
                    continue  # scaling what the rules do not send changes nothing: skip it, exactly
                local_best, local_factor = best_cost, found[w, j]
                for f in FACTORS:
                    trial = scale.copy()
                    trial[mask] = f
                    _restore(env, snap)
                    cost = _finish(env, parts, config, obs, {**proposal, "flows": flows * trial}, w, found, masks)
                    rollouts += 1
                    if local_best is None or cost < local_best:
                        local_best, local_factor = cost, f
                scale[mask] = local_factor
                found[w, j] = local_factor
                best_cost = local_best
            _restore(env, snap)
            obs, reward, terminated, truncated, _ = env.step({**proposal, "flows": flows * scale})
            total += -float(reward)
            w += 1
            if terminated or truncated:
                break
        schedule = found
        history.append(total)
        best_total = min(best_total, total)
    return {
        "episode": int(index),
        "base_cost": base,
        "best_cost": best_total,
        "gain": (base - best_total) / base,
        "rollouts": rollouts,
        "sweeps": history,
        "schedule": schedule.tolist(),
    }


def main(task="small", entropy=111, episodes=12, workers=10, sweeps=1, grouping="family", out=None):
    stamp = time.strftime("%Y%m%d_%H%M%S")
    out = Path(out) if out else ROOT / "outputs" / "rl_lab" / f"action_{grouping}_{task}_{entropy}_{stamp}"
    out.mkdir(parents=True, exist_ok=True)
    (out / "settings.json").write_text(
        json.dumps(
            {
                "task": task,
                "entropy": entropy,
                "episodes": episodes,
                "families": FAMILIES,
                "factors": FACTORS,
                "sweeps": sweeps,
                "grouping": grouping,
                "mode": "lookahead in the true simulator, schedule tail, true future",
            },
            indent=2,
        )
    )
    print(
        f"lookahead on {task}, root {entropy}, {episodes} episode(s), {sweeps} sweep(s), "
        f"grouping {grouping}, {len(FACTORS)} factors per coordinate -> {out}",
        flush=True,
    )

    t0 = time.perf_counter()
    rows = []
    with ProcessPoolExecutor(max_workers=workers) as pool:
        for row in pool.map(episode, [(task, entropy, episodes, i, sweeps, grouping) for i in range(episodes)]):
            rows.append(row)
            sweep_gains = " ".join(f"{(row['base_cost'] - s) / row['base_cost']:+.2%}" for s in row["sweeps"])
            print(
                f"  episode {row['episode']:3d}: {row['base_cost']:.4e} -> {row['best_cost']:.4e} "
                f"({row['gain']:+.2%}; by sweep: {sweep_gains})",
                flush=True,
            )
    (out / "result.json").write_text(json.dumps(rows, indent=2))
    rel = np.array([r["gain"] for r in rows])
    print(
        f"\nlookahead gain over the plain rules: {rel.mean():+.4%} "
        f"± {rel.std(ddof=1) / np.sqrt(len(rel)):.4%}, better in {int((rel > 0).sum())}/{len(rel)}"
    )
    print(f"done in {time.perf_counter() - t0:.0f} s: {out}", flush=True)
    return str(out)


if __name__ == "__main__":
    import fire

    fire.Fire(main)
